import { createServer } from 'miragejs';

const BASE_URL = 'http://127.0.0.1:8000/api/v1';

createServer({
    routes() {
        this.get(`${BASE_URL}/home-catalog`, () => {
            return [
                {
                    "id": 29,
                    "name": "Muebles",
                    "slug": "muebles",
                    "icon": "muebles.png",
                    "image": null,
                    "type": "category",
                    "capitalized_name": "Muebles",
                    "icon_url": "https://www.herrajesoeste.com/assets/images/categories/muebles.png"
                },
                {
                    "id": 1,
                    "name": "Hogar",
                    "slug": "hogar",
                    "icon": "hogar.png",
                    "image": null,
                    "type": "category",
                    "capitalized_name": "Hogar",
                    "icon_url": "https://www.herrajesoeste.com/assets/images/categories/hogar.png"
                },
                {
                    "id": 62,
                    "name": "Obra",
                    "slug": "obra",
                    "icon": "obra.png",
                    "image": null,
                    "type": "category",
                    "capitalized_name": "Obra",
                    "icon_url": "https://www.herrajesoeste.com/assets/images/categories/obra.png"
                },
            ]
        }),
        this.get(`${BASE_URL}/products`, () => {
            return {
                "data": [
                    {
                        "id": 8805,
                        "shop_category_id": 68,
                        "name": "TOR JAP 5 X 1 1/4 TEL",
                        "slug": "tor-jap-5-x-1-14-tel",
                        "sku": null,
                        "code": "TEL006",
                        "barcode": null,
                        "short_description": null,
                        "description": null,
                        "qty": 0,
                        "price": "35902.58",
                        "int_price": 3590258,
                        "formatted_price": "35.902,58",
                        "seo_title": null,
                        "seo_description": null,
                        "seo_keywords": null,
                        "image": "wIfnIO0lmTYgdvFAtgAv7FhvnK.png",
                        "fallback_image": "no-image.webp",
                        "image_url": "https://admin.herrajesoeste.com/storage/products/media/wIfnIO0lmTYgdvFAtgAv7FhvnK.png",
                        "category": {
                            "id": 68,
                            "parent_id": 63,
                            "shop_product_id": null,
                            "name": "Tornillos, bulones y mas ...",
                            "slug": "tornillos",
                            "description": null,
                            "image": null,
                            "image_url": null,
                            "icon": null,
                            "parent": {
                                "id": 63,
                                "parent_id": 62,
                                "shop_product_id": null,
                                "name": "Armado y terminación",
                                "slug": "armado-y-terminacion",
                                "description": null,
                                "image": null,
                                "image_url": null,
                                "icon": null,
                                "parent": {
                                    "id": 62,
                                    "parent_id": null,
                                    "shop_product_id": null,
                                    "name": "Obra",
                                    "slug": "obra",
                                    "description": null,
                                    "image": null,
                                    "image_url": null,
                                    "icon": null,
                                    "parent": null,
                                    "benefit": null
                                },
                                "benefit": null
                            },
                            "benefit": null
                        },
                        "tags": []
                    },
                    {
                        "id": 8803,
                        "shop_category_id": 68,
                        "name": "TOR JAP 10 X 2 (X UNIDAD)",
                        "slug": "tor-jap-10-x-2-x-unidad",
                        "sku": null,
                        "code": "TEL003",
                        "barcode": null,
                        "short_description": null,
                        "description": null,
                        "qty": 562,
                        "price": "113.93",
                        "int_price": 11393,
                        "formatted_price": "113,93",
                        "seo_title": null,
                        "seo_description": null,
                        "seo_keywords": null,
                        "image": "Hw4Js5Z1NjlrwlI4ejkeVPOY2n.png",
                        "fallback_image": "no-image.webp",
                        "image_url": "https://admin.herrajesoeste.com/storage/products/media/Hw4Js5Z1NjlrwlI4ejkeVPOY2n.png",
                        "category": {
                            "id": 68,
                            "parent_id": 63,
                            "shop_product_id": null,
                            "name": "Tornillos, bulones y mas ...",
                            "slug": "tornillos",
                            "description": null,
                            "image": null,
                            "image_url": null,
                            "icon": null,
                            "parent": {
                                "id": 63,
                                "parent_id": 62,
                                "shop_product_id": null,
                                "name": "Armado y terminación",
                                "slug": "armado-y-terminacion",
                                "description": null,
                                "image": null,
                                "image_url": null,
                                "icon": null,
                                "parent": {
                                    "id": 62,
                                    "parent_id": null,
                                    "shop_product_id": null,
                                    "name": "Obra",
                                    "slug": "obra",
                                    "description": null,
                                    "image": null,
                                    "image_url": null,
                                    "icon": null,
                                    "parent": null,
                                    "benefit": null
                                },
                                "benefit": null
                            },
                            "benefit": null
                        },
                        "tags": []
                    },
                    {
                        "id": 8813,
                        "shop_category_id": 68,
                        "name": "TOR JAP 6 X 1 FN (X 500)",
                        "slug": "tor-jap-6-x-1-fn-x-500",
                        "sku": null,
                        "code": "TEL014",
                        "barcode": null,
                        "short_description": null,
                        "description": null,
                        "qty": 4,
                        "price": "19226.30",
                        "int_price": 1922630,
                        "formatted_price": "19.226,30",
                        "seo_title": null,
                        "seo_description": null,
                        "seo_keywords": null,
                        "image": "CofotObuU9TmNZwzoUf102aHWc.png",
                        "fallback_image": "no-image.webp",
                        "image_url": "https://admin.herrajesoeste.com/storage/products/media/CofotObuU9TmNZwzoUf102aHWc.png",
                        "category": {
                            "id": 68,
                            "parent_id": 63,
                            "shop_product_id": null,
                            "name": "Tornillos, bulones y mas ...",
                            "slug": "tornillos",
                            "description": null,
                            "image": null,
                            "image_url": null,
                            "icon": null,
                            "parent": {
                                "id": 63,
                                "parent_id": 62,
                                "shop_product_id": null,
                                "name": "Armado y terminación",
                                "slug": "armado-y-terminacion",
                                "description": null,
                                "image": null,
                                "image_url": null,
                                "icon": null,
                                "parent": {
                                    "id": 62,
                                    "parent_id": null,
                                    "shop_product_id": null,
                                    "name": "Obra",
                                    "slug": "obra",
                                    "description": null,
                                    "image": null,
                                    "image_url": null,
                                    "icon": null,
                                    "parent": null,
                                    "benefit": null
                                },
                                "benefit": null
                            },
                            "benefit": null
                        },
                        "tags": []
                    },
                    {
                        "id": 7676,
                        "shop_category_id": 68,
                        "name": "TOR JAP 6 X 3/4 (X 100)",
                        "slug": "tor-jap-6-x-34-x-100",
                        "sku": null,
                        "code": "HGR02",
                        "barcode": null,
                        "short_description": null,
                        "description": null,
                        "qty": 15,
                        "price": "15665.87",
                        "int_price": 1566587,
                        "formatted_price": "15.665,87",
                        "seo_title": null,
                        "seo_description": null,
                        "seo_keywords": null,
                        "image": "ka7tJhwPNmZzGkZbqeElHLYnKQ.png",
                        "fallback_image": "no-image.webp",
                        "image_url": "https://admin.herrajesoeste.com/storage/products/media/ka7tJhwPNmZzGkZbqeElHLYnKQ.png",
                        "category": {
                            "id": 68,
                            "parent_id": 63,
                            "shop_product_id": null,
                            "name": "Tornillos, bulones y mas ...",
                            "slug": "tornillos",
                            "description": null,
                            "image": null,
                            "image_url": null,
                            "icon": null,
                            "parent": {
                                "id": 63,
                                "parent_id": 62,
                                "shop_product_id": null,
                                "name": "Armado y terminación",
                                "slug": "armado-y-terminacion",
                                "description": null,
                                "image": null,
                                "image_url": null,
                                "icon": null,
                                "parent": {
                                    "id": 62,
                                    "parent_id": null,
                                    "shop_product_id": null,
                                    "name": "Obra",
                                    "slug": "obra",
                                    "description": null,
                                    "image": null,
                                    "image_url": null,
                                    "icon": null,
                                    "parent": null,
                                    "benefit": null
                                },
                                "benefit": null
                            },
                            "benefit": null
                        },
                        "tags": []
                    },
                    {
                        "id": 7677,
                        "shop_category_id": 68,
                        "name": "TOR JAP 8 X 3 H",
                        "slug": "tor-jap-8-x-3-h",
                        "sku": null,
                        "code": "HGR03",
                        "barcode": null,
                        "short_description": null,
                        "description": null,
                        "qty": 0,
                        "price": "46585.00",
                        "int_price": 4658500,
                        "formatted_price": "46.585,00",
                        "seo_title": null,
                        "seo_description": null,
                        "seo_keywords": null,
                        "image": "Ai0LgU5DBLXCoi0nWRN2G4pYlw.png",
                        "fallback_image": "no-image.webp",
                        "image_url": "https://admin.herrajesoeste.com/storage/products/media/Ai0LgU5DBLXCoi0nWRN2G4pYlw.png",
                        "category": {
                            "id": 68,
                            "parent_id": 63,
                            "shop_product_id": null,
                            "name": "Tornillos, bulones y mas ...",
                            "slug": "tornillos",
                            "description": null,
                            "image": null,
                            "image_url": null,
                            "icon": null,
                            "parent": {
                                "id": 63,
                                "parent_id": 62,
                                "shop_product_id": null,
                                "name": "Armado y terminación",
                                "slug": "armado-y-terminacion",
                                "description": null,
                                "image": null,
                                "image_url": null,
                                "icon": null,
                                "parent": {
                                    "id": 62,
                                    "parent_id": null,
                                    "shop_product_id": null,
                                    "name": "Obra",
                                    "slug": "obra",
                                    "description": null,
                                    "image": null,
                                    "image_url": null,
                                    "icon": null,
                                    "parent": null,
                                    "benefit": null
                                },
                                "benefit": null
                            },
                            "benefit": null
                        },
                        "tags": []
                    },
                ]
            }
        })
    }
});